ProductTracking/Controllers/AnalyticsController.cs
using ProductTracking.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductTracking.Controllers
{
    public class AnalyticsController : Controller
    {
        // GET: Analytics
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult HabitesDashboard()
        {

            using (var ctx = new ApplicationDbContext())
            {
                var fromString = DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:00.000";
                var toStrings = DateTime.Now.ToString("yyyy-MM-dd") + " 09:00:00.000";
                var fromGraceString = DateTime.Now.ToString("yyyy-MM-dd") + " 09:00:01.000";
                var GraceTime= DateTime.Now.ToString("yyyy-MM-dd") + " 09:30:00.000";
                var Latefromtime= DateTime.Now.ToString("yyyy-MM-dd") + " 09:30:01.000";
                var LateEndtimetime = DateTime.Now.ToString("yyyy-MM-dd") + " 23:59:00.000";

              
                int totalEmployeesBeingontime = ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "00:00:00", "09:00:00", "00:00:00")).FirstOrDefault();
                ViewBag.OntimeCount = totalEmployeesBeingontime;
                
                int totalEmployeeslate = ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "09:00:01", "09:30:00", "09:00:00")).FirstOrDefault();
                ViewBag.latetimeCount = totalEmployeeslate;

                int GraceTimePunch = ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "09:30:01", "23:59:59", "09:30:00")).FirstOrDefault();
                ViewBag.Gracetime = GraceTimePunch;

                string TodayDate = DateTime.Now.ToString("yyyy/MM/dd");
                ViewBag.TotalEmployees = ctx.Database.SqlQuery<Int32>(new QueryStrings().GetPresentCount(TodayDate.Replace('-', '/'))).FirstOrDefault();
               


            }
            return View();
        }
        public ActionResult HabitesDashboardPie()
        {
            ArrayList OnTimestatistics = new ArrayList();
            using (var ctx = new ApplicationDbContext())
            {
                string[] data = new string[] { "Before 8:00 AM", " 8:00 AM to 8:30 AM", " 8:30 AM to 9:00 AM", " 9:00 AM to 9:30 AM", " 9:30 AM to 10:00 AM", " 10:00 AM to 10:30 AM", " After 11:00 AM " };

                List<Int32> Countdata = new List<Int32>();
                #region commented by Varaprasad
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 08:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 08:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 08:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 08:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 09:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 09:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 09:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 09:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 10:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 10:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 10:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 10:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 11:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery(DateTime.Now.ToString("yyyy-MM-dd") + " 11:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:00.000")).FirstOrDefault());



                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 00:00:00.000", DateTime.Now.ToString("yyyy-MM-dd") + " 08:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 08:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 08:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 08:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 09:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 09:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 09:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 09:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 10:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 10:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 10:30:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 10:30:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 11:00:00.000")).FirstOrDefault());
                //Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetTimeQuery("2018-02-22" + " 11:00:01.000", DateTime.Now.ToString("yyyy-MM-dd") + " 23:59:59.000")).FirstOrDefault());
                #endregion
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "00:00:00", "08:00:00", "00:00:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "08:00:01", "08:30:00", "08:00:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "08:30:01", "09:00:00", "08:30:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "09:00:01", "09:30:00", "09:00:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "09:30:01", "10:00:00", "09:30:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "10:00:01", "10:30:00", "10:00:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "10:30:01", "11:00:00", "10:30:00")).FirstOrDefault());
                Countdata.Add(ctx.Database.SqlQuery<Int32>(new QueryStrings().GetDateTimeQuery(DateTime.Now.ToString("dd-MM-yyyy"), "11:00:01", "23:59:59", "11:00:00")).FirstOrDefault());


                int[] count = Countdata.ToArray();


                for (int i = 0; i < data.Count(); i++)
                {

                    string time_cat = data[i].ToString();
                    string emp_num = count[i].ToString();
                    OnTimestatistics.Add(new
                    {
                        time_cat,
                        emp_num
                    });
                }
            }

            return Json(OnTimestatistics, JsonRequestBehavior.AllowGet);
        }
        public ActionResult HabitesDashboardOntimevsDelay()
        {
            ArrayList OntimevsDelay = new ArrayList();
            string[] months = new string[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
            int[] planned = new int[] { 19, 71, 106, 129, 144, 176, 135, 148, 216, 194, 95, 54 };
            int[] unplanned = new int[] { 83, 78, 98, 93, 106, 84, 105, 104, 91, 83, 106, 92 };
            OntimevsDelay.Add(months);
            OntimevsDelay.Add(planned);
            OntimevsDelay.Add(unplanned);
            return Json(OntimevsDelay, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EffortDashboard()
        {
            return View();
        }
        public ActionResult EffortDashboardPie()
        {
            ArrayList Effortstatistics = new ArrayList();

            string[] data = new string[] { "Employee Working Hours", "Employee Leave hours", "Employee Work from Home Hours", "2 hours permission Include Hours" };

            string[] count = new string[] { "4000", "200", "500", "50" };

            for (int i = 0; i < data.Count(); i++)
            {

                string time_cat = data[i].ToString();
                string emp_num = count[i].ToString();
                Effortstatistics.Add(new
                {
                    time_cat,
                    emp_num
                });
            }

            return Json(Effortstatistics, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EffortDashboardWorkingVsLeavehours()
        {
            ArrayList WorkingVsLeavehours = new ArrayList();
            string[] months = new string[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
            int[] planned = new int[] { 4900, 7100, 1006, 1029, 1044, 1076, 1305, 2148, 2106, 3194, 2395, 4554 };

ProductTracking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excelra Attendance Dashboard</title>
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/select2/select2.min.css" rel="stylesheet" />
    <link href="~/Content/App/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/App/css/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/App/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/App/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/App/css/_all-skins.min.css" rel="stylesheet" />
    <link href="~/Content/App/css/custom.css" rel="stylesheet" />
    <style>
        .loading{
            background-image:url('@Url.Content("~/Content/App/images/loading.gif")');
            background-repeat: no-repeat;
            background-size: 48px 48px;
        }
    </style>
    @RenderSection("head", required: false)
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>E</b>A</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg" style="font-size:15px"><b>E</b> Attendence and Analytics</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Content/App/images/avatar5.png" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Login User</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form hidden">
                    <div class="input-group hidden">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li>
                        <a href="@Url.Action("Index","Home")">
                            <i class="fa fa-dashboard"></i> <span>TV Dashboard</span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("MyEmployeeDashboard","Analytics")">
                            <i class="fa fa-user-plus"></i> <span>My Dashboard</span>
                        </a>
                    </li>

                    @*<li>
                        <a href="@Url.Action("Index","Analytics")">
                            <i class="fa fa-calendar-times-o"></i> <span>Leave Dashboard</span>
                        </a>
                    </li>*@
                    <li>
                        <a href="@Url.Action("HabitesDashboard","Analytics")">
                            <i class="fa fa-clock-o"></i> <span>Time Dashboard</span>
                        </a>
                    </li>
                    @*<li>
                        <a href="@Url.Action("EffortDashboard","Analytics")">
                            <i class="fa fa-users"></i> <span>Effort Dashboard</span>
                        </a>
                    </li>*@
                    @*<li>
                        <a href="@Url.Action("ComparisonDashboard","Analytics")">
                            <i class="fa fa-retweet"></i> <span>Comparison Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("LeaveEncashDashboard","Analytics")">
                            <i class="fa fa-money"></i> <span>Leave Encash Dashboard</span>
                        </a>
                    </li>*@
                    
                    @*<li>
                        <a href="@Url.Action("DelayedSignInDashboard","Analytics")">
                            <i class="fa fa-hourglass-end"></i> <span>Delayed Signin Dashboard</span>
                        </a>
                    </li>*@
                    <li>
                        <a href="@Url.Action("OrganizationDashboard","Analytics")">
                            <i class="fa fa-university"></i> <span>Organization Dashboard</span>
                        </a>
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper">
            @RenderSection("heading", required: false)
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
        </div>

        <footer class="footer">
            <div style="padding-top:5px;padding-left:10px;">
                <p>&copy; @DateTime.Now.Year - Powered By Excelra Knowledge Solutions</p>
            </div>
        </footer>
    </div>

    <div id="loadingDiv" style="display: none;" class="hold-transition">
        <img src="~/Content/App/images/ajax-loader.gif" />
    </div>

    <script src="~/Content/App/js/jquery-1.12.1.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Content/select2/select2.full.min.js"></script>
    <!--<script src="~/Content/App/js/highcharts.js"></script> -->
    <script src="~/Content/App/js/highcharts.src.js"></script>
    <script src="~/Content/App/js/moment.js"></script>
    <script src="~/Content/App/js/daterangepicker.js"></script>
    <script src="~/Content/App/js/app.min.js"></script>
    <script src="~/Content/App/js/demo.js"></script>

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        function initSignalR() {
            var chat = $.connection.liveHub;
            chat.client.reload = function (msg) {
                location.reload();
            };
            $.connection.hub.start().done(function () {
            });
        }
        initSignalR();

        var slideToTop = $("<div />");
        slideToTop.html('<i class="fa fa-chevron-up"></i>');
        slideToTop.css({
            position: 'fixed',
            bottom: '20px',
            right: '25px',
            width: '40px',
            height: '40px',
            color: '#eee',
            'font-size': '',
            'line-height': '40px',
            'text-align': 'center',
            'background-color': '#222d32',
            cursor: 'pointer',
            'border-radius': '5px',
            'z-index': '99999',
            opacity: '.7',
            'display': 'none'
        });
        slideToTop.on('mouseenter', function () {
            $(this).css('opacity', '1');
        });
        slideToTop.on('mouseout', function () {
            $(this).css('opacity', '.7');
        });
        $('.wrapper').append(slideToTop);
        $(window).scroll(function () {
            if ($(window).scrollTop() >= 150) {
                if (!$(slideToTop).is(':visible')) {
                    $(slideToTop).fadeIn(500);
                }
            } else {
                $(slideToTop).fadeOut(500);
            }
        });
        $(slideToTop).click(function () {
            $("body").animate({
                scrollTop: 0
            }, 500);
        });
        $(".sidebar-menu li:not(.treeview) a").click(function () {
            var $this = $(this);
            var target = $this.attr("href");
            if (typeof target === 'string') {
                $("body").animate({
                    scrollTop: ($(target).offset().top) + "px"
                }, 500);
            }
        });

        $('.select2').select2({
            placeholder: {
                id: '-1', // the value of the option
                text: 'Select an option'
            },
            allowClear: true
        });
    </script>
</body>
</html>